meta_product_name: "Meehir Patel"
meta_title: "Meehir Patel | Product Manager & Web Developer"
meta_description: "I'm Meehir Patel, product manager and web developer. I help businesses build their brands online through creating engaging, high converting websites."
meta_image: "profile.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
